name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: my-resume-app
        run: npm install
      - name: Build React app
        working-directory: my-resume-app
        run: npm run build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        with:
          publish_dir: ./my-resume-app/build
          github_token: ${{ secrets.GITHUB_TOKEN }}




